[package]
name = "cpcs-analyzer"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.103"
aya = "0.14.0"
cpcs-analyzer-common = { path = "../cpcs-analyzer-common", features = ["user"] }
ctor = "1.0.8"
libc = "0.2.186"
log = "0.4.33"
mio = { version = "1.2.1", features = ["os-ext"] }
rustix = { version = "1.1.4", features = ["process"] }

[build-dependencies]
anyhow = "1.0.103"
cpcs-analyzer-ebpf = { path = "../cpcs-analyzer-ebpf" }
