[package]
name = "cpcs-analyzer"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.102"
aya = "0.13.1"
cpcs-analyzer-common = { path = "../cpcs-analyzer-common", features = ["user"] }
ctor = "1.0.6"
libc = "0.2.186"
log = "0.4.29"
mio = { version = "1.2.0", features = ["os-ext"] }

[build-dependencies]
anyhow = "1.0.102"
cpcs-analyzer-ebpf = { path = "../cpcs-analyzer-ebpf" }
